- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  setPreference: false # DeltaV - Disable Senior Roles round start selection
<<<<<<< HEAD
  # requirements:
    # - !type:RoleTimeRequirement
      # role: JobAtmosphericTechnician
      # time: 21600 #6 hrs
    # - !type:RoleTimeRequirement
      # role: JobStationEngineer
      # time: 21600 #6 hrs
    # - !type:DepartmentTimeRequirement
      # department: Engineering
      # time: 216000 # 60 hrs
=======
  requirements:
    - !type:CharacterPlaytimeRequirement
      tracker: JobAtmosphericTechnician
      min: 21600 #6 hrs
    - !type:CharacterPlaytimeRequirement
      tracker: JobStationEngineer
      min: 21600 #6 hrs
    - !type:CharacterDepartmentTimeRequirement
      department: Engineering
      min: 216000 # 60 hrs
>>>>>>> EE-Personal/master
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    head: ClothingHeadHatBeretEngineering
    jumpsuit: ClothingUniformJumpsuitSeniorEngineer
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  innerClothingSkirt: ClothingUniformJumpskirtSeniorEngineer
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
