- type: job
  id: Zookeeper
  name: job-name-zookeeper
  description: job-description-zookeeper
  playTimeTracker: JobZookeeper
<<<<<<< HEAD
  # requirements:
    # - !type:OverallPlaytimeRequirement
      # time: 7200 #DeltaV 2 hours
=======
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 7200 #DeltaV 2 hours
>>>>>>> EE-Personal/master
  startingGear: ZookeeperGear
  icon: "JobIconZookeeper"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Zookeeper # DeltaV - Add Zookeeper access

- type: startingGear
  id: ZookeeperGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSafari
    back: ClothingBackpackFilled
    head: ClothingHeadSafari
    shoes: ClothingShoesColorWhite
    id: ZookeeperPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpsuitSafari
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
