- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  antagAdvantage: 2 # DeltaV - Reduced TC: Security Radio and Access
<<<<<<< HEAD
  # requirements:
    # - !type:OverallPlaytimeRequirement
      # time: 36000 # 10 hrs
    # - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
      # department: Security
      # time: 14400 # 4 hours
=======
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 36000 # 10 hrs
    - !type:CharacterDepartmentTimeRequirement # DeltaV - Security dept time requirement
      department: Security
      min: 14400 # 4 hours
>>>>>>> EE-Personal/master
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Lawyer
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackLawyerFilled #DeltaV - stamp included
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
    # TODO add copy of space law
  inhand:
    - BriefcaseBrownFilled
  innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelLawyerFilled #DeltaV - stamp included
  duffelbag: ClothingBackpackDuffelLawyerFilled #DeltaV - stamp included
